In [202]:
import numpy as np
import pandas as pd

In [204]:
df =pd.read_excel('../Data/independent-house.xlsx')

In [205]:
df.head()

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,...,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,...,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,...,"Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,...,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,...,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,...,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [206]:
df.shape

(967, 21)

In [208]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 967 entries, 0 to 966
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    967 non-null    object
 1   link             967 non-null    object
 2   society          390 non-null    object
 3   price            967 non-null    object
 4   rate             957 non-null    object
 5   area             967 non-null    object
 6   areaWithType     967 non-null    object
 7   bedRoom          967 non-null    object
 8   bathroom         967 non-null    object
 9   balcony          967 non-null    object
 10  additionalRoom   576 non-null    object
 11  address          962 non-null    object
 12  noOfFloor        947 non-null    object
 13  facing           660 non-null    object
 14  agePossession    967 non-null    object
 15  nearbyLocations  845 non-null    object
 16  description      967 non-null    object
 17  furnishDetails   728 non-null    object
 18  features         658 non-null    object
 19  rating           846 non-null    object
 20  property_id      967 non-null    object
dtypes: object(21)
memory usage: 158.8+ KB

In [212]:
df.duplicated().sum()

13

In [214]:
df.isnull().sum()

property_name        0
link                 0
society            577
price                0
rate                10
area                 0
areaWithType         0
bedRoom              0
bathroom             0
balcony              0
additionalRoom     391
address              5
noOfFloor           20
facing             307
agePossession        0
nearbyLocations    122
description          0
furnishDetails     239
features           309
rating             121
property_id          0
dtype: int64

In [216]:
# dropping the link & PropertyID column 

df.drop(columns =['link','property_id'] ,inplace =True)

In [218]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [220]:
df.shape

(967, 19)

In [222]:
df =df.drop_duplicates()

In [224]:
df.duplicated().sum()

0

In [226]:
# Renaming the rate column as area_per_sq
df.rename(columns ={'rate':'price_per_sqft'} ,inplace =True)

In [228]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [229]:
# Now we will gp column wise to perform the data cleaning 
df['society'].value_counts().shape

(180,)

In [232]:
df['society'].isnull().sum()

572

In [234]:
 # using reg we will remove the columns having the (* ,or the ratings in our society columns )
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★','', str(name)).strip()).str.lower()

In [236]:
df['society'].value_counts()

society
nan                                    572
vipul tatvam villa                      19
international city by sobha phase 2     19
international city by sobha phase 1     15
emaar mgf marbella                      13
                                      ...
dlf city plot phase 4                    1
sai kripa floors 5                       1
rajendra park gurgaon                    1
krishna palace                           1
naman residency                          1
Name: count, Length: 178, dtype: int64

In [238]:
df['society'] =df['society'].str.replace('nan','Independent')

In [239]:
df['society'].value_counts().shape

(178,)

In [240]:
# Now second column of price 
df['price'].value_counts()

price
3.5 Crore     19
5.5 Crore     17
6.5 Crore     16
6 Crore       14
8 Crore       13
              ..
8.8 Crore      1
1.34 Crore     1
46 Lac         1
2.6 Crore      1
2.98 Crore     1
Name: count, Length: 302, dtype: int64

In [241]:
df =df[df['price']!='Price on Request']

In [242]:
df['price'].value_counts()

price
3.5 Crore     19
5.5 Crore     17
6.5 Crore     16
6 Crore       14
70 Lac        13
              ..
8.8 Crore      1
1.34 Crore     1
46 Lac         1
2.6 Crore      1
2.98 Crore     1
Name: count, Length: 301, dtype: int64

In [243]:
# writing a function to convert the lakh into crore 
def converting_lakh_into_crore(X):
    if type(X) ==float:
        # if isinastance(X,float)
        return X
    else:
        if X[1] =='Lac':
            return (round(float(X[0])/100,2))
                    
        else:
            return(round(float(X[0]) ,2))

In [244]:
df['price'] =df['price'].str.split(' ').apply(converting_lakh_into_crore)

In [245]:
df.sample(4)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
296,3 Bedroom House for sale in Farukhnagar,Independent,0.52,"₹ 5,778/sq.ft.",(84 sq.m.) Plot Area,Plot area 100(83.61 sq.m.),3 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Farukhnagar, Gurgaon, Haryana",2 Floors,NaN,0 to 1 Year Old,"['Dr. Manish Pandey', 'Verma Dental Clinic', '...",Interested to sell independent house/villa.Pla...,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
318,3 Bedroom House for sale in Rajendra Park,Independent,1.15,"₹ 3,285/sq.ft.",(325 sq.m.) Carpet Area,Carpet area: 3500 (325.16 sq.m.),3 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Rajendra Park Block B, Sector 105, Rajendra Pa...",1 Floors,NaN,undefined,NaN,Best in class property available at rajendra p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
382,4 Bedroom House for sale in Sector 67 Gurgaon,Independent,3.00,"₹ 11,904/sq.ft.",(234 sq.m.) Carpet Area,Carpet area: 2520 (234.12 sq.m.),4 Bedrooms,4 Bathrooms,No Balcony,NaN,"Sector 67, Gurgaon, Haryana, India, Sector 67 ...",3 Floors,North-East,undefined,"['Sri Radhe Krishna Temple', 'Kamal Hospital a...",Beautiful house with ready to move option.All ...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4.5 out of..."
911,5 Bedroom House for sale in Sector 14 Gurgaon,Independent,5.50,"₹ 16,975/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.)Built Up area: 355 ...,5 Bedrooms,4 Bathrooms,2 Balconies,Study Room,"00001425, Sector 14 Gurgaon, Gurgaon, Haryana",2 Floors,East,10+ Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",House for sale plot size 360 sqyard plot rate ...,NaN,"['Maintenance Staff', 'Water Storage', 'Visito...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [246]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 22,222/sq.ft.    13
₹ 11,111/sq.ft.    11
₹ 33,333/sq.ft.    11
₹ 10,000/sq.ft.    10
₹ 26,667/sq.ft.     6
                   ..
₹ 7,576/sq.ft.      1
₹ 11,556/sq.ft.     1
₹ 10,378/sq.ft.     1
₹ 11,888/sq.ft.     1
₹ 33,129/sq.ft.     1
Name: count, Length: 727, dtype: int64

In [247]:
# Now Dealing the price_per_sqft column in this we will remove the unwanted values 
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹' ,'').str.replace(',','').str.strip().astype('float')
df['price_per_sqft']

0       20115.0
1      105751.0
2       38251.0
3       43066.0
4       53763.0
         ...
962     30556.0
963     31481.0
964     33333.0
965     33129.0
966     14815.0
Name: price_per_sqft, Length: 944, dtype: float64

In [248]:
# Now dealing with the bedroom column 
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,Independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,Independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,Independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,Independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [249]:
df['bedRoom'] =df['bedRoom'].str.split(' ').str.get(0)

In [262]:
df

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,Independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,Independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,Independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,Independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
962,4 Bedroom House for sale in Sector 26 Gurgaon,dlf city phase 1,5.50,30556.0,(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),4,4 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room","Sector 26 Gurgaon, Gurgaon, Haryana",2 Floors,North-East,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","Residential house, g block, dlf phase-1, gurga...","['10 Light', 'No AC', 'No Bed', 'No Chimney', ...","['Feng Shui / Vaastu Compliant', 'High Ceiling...",NaN
963,3 Bedroom House for sale in DLF Phase 2,dlf city plots phase 2,4.25,31481.0,(125 sq.m.) Plot Area,Plot area 150(125.42 sq.m.),3,2 Bathrooms,3 Balconies,Study Room,"DLF Phase 2, Gurgaon, Haryana",2 Floors,North,10+ Year Old,"['Sahara Mall', 'Delhi Public School', 'Privat...","Residential house, k block, dlf phase-2, gurga...",NaN,"['High Ceiling Height', 'Maintenance Staff', '...","['Environment5 out of 5', 'Safety5 out of 5', ..."
964,3 Bedroom House for sale in Sector 26 Gurgaon,dlf city phase 1,4.50,33333.0,(125 sq.m.) Plot Area,Plot area 150(125.42 sq.m.),3,3 Bathrooms,2 Balconies,"Study Room,Servant Room","Sector 26 Gurgaon, Gurgaon, Haryana",2 Floors,East,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","Residential house, e block 150 sq.Yds , dlf ph...","['6 Fan', '20 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
965,3 Bedroom House for sale in Sector 26 Gurgaon,dlf city phase 1,3.25,33129.0,(91 sq.m.) Plot Area,Plot area 109(91.14 sq.m.),3,3 Bathrooms,3 Balconies,Study Room,"Sector 26 Gurgaon, Gurgaon, Haryana",2 Floors,West,10+ Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","Residential house, e block, dlf phase-1, gurga...","['5 Fan', '16 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
966,3 Bedroom House for sale in Bissar,silverglades tarudhan valley golf resort,3.60,14815.0,(226 sq.m.) Plot Area,Plot area 270(225.75 sq.m.),3,3 Bathrooms,2 Balconies,"Pooja Room,Study Room,Servant Room,Others","Bissar, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,This 3 bhk house for sale in bissar is an idea...,"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'...",NaN

In [263]:
df['bedRoom'].value_counts()

bedRoom
4     230
5     182
3     146
2      87
6      80
9      44
1      38
8      33
7      30
12     27
10     21
16     11
13      4
18      2
19      2
11      2
20      1
21      1
36      1
34      1
14      1
Name: count, dtype: int64

In [264]:
# next bathroom column 
df['bathroom'].value_counts()

bathroom
4 Bathrooms     225
3 Bathrooms     164
5 Bathrooms     131
2 Bathrooms     112
6 Bathrooms      82
1 Bathroom       64
9 Bathrooms      41
7 Bathrooms      37
8 Bathrooms      26
12 Bathrooms     21
10 Bathrooms     11
16 Bathrooms      7
18 Bathrooms      4
13 Bathrooms      4
11 Bathrooms      4
20 Bathrooms      3
17 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
36 Bathrooms      1
34 Bathrooms      1
Name: count, dtype: int64

In [265]:

df['bathroom'] =df['bathroom'].str.split(' ').str.get(0).str.strip()

In [266]:
df['bathroom']

0       4
1       4
2      10
3      21
4      12
       ..
962     4
963     2
964     3
965     3
966     3
Name: bathroom, Length: 944, dtype: object

In [267]:
df['bathroom'].isnull().sum()

0

In [268]:
# Next we will go to the 
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,Independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,Independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,Independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,Independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [276]:
df['balcony'].value_counts()

balcony
3+ Balconies    352
2 Balconies     217
3 Balconies     157
No Balcony      114
1 Balcony       104
Name: count, dtype: int64

In [278]:
df['balcony'] =df['balcony'].str.split(' ').str.get(0).str.replace('No' ,'0').str.extract(r'(\d+)')

In [280]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,Independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,Independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,Independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,Independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [282]:
# Now to next column Additional Column

df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     80
Pooja Room,Study Room,Servant Room,Store Room    59
Others                                           58
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               32
Store Room                                       31
Pooja Room,Study Room,Servant Room,Others        29
Pooja Room,Servant Room                          23
Study Room                                       18
Study Room,Servant Room                          18
Servant Room,Store Room                          12
Pooja Room,Study Room                            11
Pooja Room,Store Room                            11
Pooja Room,Others                                11
Servant Room,Pooja Room                           8
Servant Room,Others                               8
Pooja Room,Servant Room,Store Room                7
Pooja Room,Store Room,Study Room,Servant Room     7
Store Room,Servant Room                           6
Study Room,Servant Room,Pooja Room,Store Room     6
Servant Room,Pooja Room,Store Room                6
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Study Room,Pooja Room,Servant Room                5
Servant Room,Store Room,Pooja Room                4
Study Room,Servant Room,Store Room                4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room,Pooja Room     4
Pooja Room,Study Room,Others                      4
Store Room,Pooja Room                             4
Pooja Room,Study Room,Store Room                  3
Study Room,Servant Room,Pooja Room                3
Study Room,Others                                 3
Study Room,Pooja Room,Servant Room,Store Room     3
Study Room,Pooja Room,Store Room,Servant Room     2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Servant Room,Others                    2
Store Room,Pooja Room,Study Room,Servant Room     2
Study Room,Pooja Room                             2
Store Room,Pooja Room,Study Room                  2
Store Room,Pooja Room,Servant Room                2
Servant Room,Study Room,Pooja Room                2
Study Room,Pooja Room,Store Room                  2
Study Room,Store Room                             1
Study Room,Store Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Servant Room,Study Room,Store Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: count, dtype: int64

In [284]:
df['additionalRoom'].isnull().sum()

379

In [286]:
df['additionalRoom'] =df['additionalRoom'].fillna('NotAvailable')

In [288]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,Independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,Independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,Independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,Independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [290]:
# Now no_of_floors Columns 
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [292]:
df['floorNum']

0      3 Floors
1      2 Floors
2      5 Floors
3      5 Floors
4      5 Floors
         ...
962    2 Floors
963    2 Floors
964    2 Floors
965    2 Floors
966    2 Floors
Name: floorNum, Length: 944, dtype: object

In [294]:
df['floorNum'].value_counts()

floorNum
3 Floors     299
2 Floors     281
1 Floors     179
4 Floors     130
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
11 Floors      2
12 Floors      2
10 Floors      2
16 Floors      1
51 Floors      1
41 Floors      1
27 Floors      1
20 Floors      1
13 Floors      1
21 Floors      1
02 Floors      1
33 Floors      1
Name: count, dtype: int64

In [296]:
df['floorNum'] =df['floorNum'].str.split(' ').str.get(0)

In [298]:
df['floorNum']

0      3
1      2
2      5
3      5
4      5
      ..
962    2
963    2
964    2
965    2
966    2
Name: floorNum, Length: 944, dtype: object

In [300]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,Independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,Independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,Independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,Independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [302]:
# Now we will work with facing columns 
df['facing'].value_counts()

facing
East          175
North-East    156
North         107
West           72
North-West     43
South-East     37
South          33
South-West     24
Name: count, dtype: int64

In [304]:
df['facing'] = df['facing'].fillna('NotAvailable')

In [306]:
df['facing']

0        North-East
1      NotAvailable
2              West
3             North
4              West
           ...
962      North-East
963           North
964            East
965            West
966    NotAvailable
Name: facing, Length: 944, dtype: object

In [308]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,Independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2,NotAvailable,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,Independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,Independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,Independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [310]:
# Now in this also we will add a column 
df['area'] = round((df['price']*10000000)/df['price_per_sqft'])

In [312]:
df['facing'].fillna('NA',inplace=True)

C:\Users\rajni\AppData\Local\Temp\ipykernel_9452\3692945726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)

In [314]:
df.insert(loc=1 ,column ='property_type' ,value ='house')

In [316]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,Independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2,NotAvailable,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,Independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,Independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,Independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [318]:
df.shape

(944, 20)

In [320]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 944 entries, 0 to 966
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    944 non-null    object
 1   property_type    944 non-null    object
 2   society          944 non-null    object
 3   price            944 non-null    float64
 4   price_per_sqft   944 non-null    float64
 5   area             944 non-null    float64
 6   areaWithType     944 non-null    object
 7   bedRoom          944 non-null    object
 8   bathroom         944 non-null    object
 9   balcony          944 non-null    object
 10  additionalRoom   944 non-null    object
 11  address          939 non-null    object
 12  floorNum         925 non-null    object
 13  facing           944 non-null    object
 14  agePossession    944 non-null    object
 15  nearbyLocations  829 non-null    object
 16  description      944 non-null    object
 17  furnishDetails   714 non-null    object
 18  features         646 non-null    object
 19  rating           824 non-null    object
dtypes: float64(3), object(17)
memory usage: 154.9+ KB

In [324]:
df.to_csv('house_cleaned.csv',index=False)