In [1]:
import pandas as pd
import numpy as np

In [27]:
df_flats = pd.read_csv('flats_cleaned.csv')
df_house =pd.read_csv('house_cleaned.csv')

In [11]:
df_house.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,nooffloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3.0,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,Independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2.0,NotAvailable,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,Independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,Independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5.0,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,Independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [21]:
df =pd.concat([df_flats,df_house],ignore_index=True)

In [23]:
df.sample(9)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,...,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,additonalRoom,nooffloor
1435,3 BHK Flat in Sohna,flat,signature global park,0.90,6254.0,1439.1,Carpet area: 1439 (133.69 sq.m.),3,3,3,...,3.0,North-West,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Signature global park in sohna, gurgaon is a r...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of...",Pooja Room,NaN
1381,3 BHK Flat in Sector 48 Gurgaon,flat,parsvnath green ville,1.50,8787.0,1707.1,Super Built up area 1707(158.59 sq.m.)Built Up...,3,3,3,...,1.0,North,10+ Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Parsvnath green ville is one of the most popul...,"['1 Water Purifier', '7 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Construction4 out of...",not available,NaN
3651,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,6.00,22222.0,2700.0,Plot area 300(250.84 sq.m.),5,4,3,...,NaN,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",This 5 bhk house for sale in sector 70a gurgao...,"['1 Fan', '1 Geyser', '1 Light', '1 Chimney', ...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment5 out of 5', 'Lifestyle4 out of 5...",NaN,3.0
767,3 BHK Flat in Sector 48 Gurgaon,flat,bestech park view city,2.70,11713.0,2305.1,Super Built up area 2305(214.14 sq.m.)Built Up...,3,3,3+,...,7.0,North-East,1 to 5 Year Old,"['Rapid Metro Sector 56', 'Sapphire Mall', 'Om...",Looking for a 3 bhk property for sale in gurga...,"['3 Wardrobe', '1 Water Purifier', '1 Sofa', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of...","Study Room,Servant Room",NaN
342,3 BHK Flat in Sector 108 Gurgaon,flat,experion the heartsong,1.36,6542.0,2078.9,Super Built up area 1758(163.32 sq.m.)Carpet a...,3,2,3+,...,2.0,NaN,1 to 5 Year Old,"['Galleria 108 Mall', 'Dwarka Expressway', 'Ce...",3bhk 3baths residential apartment for sale in ...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Lift(s)', 'Centrally Air Conditioned', 'Main...","['Green Area5 out of 5', 'Construction4 out of...","Study Room,Servant Room",NaN
3603,2 Bedroom House for sale in Sector-33 Sohna,house,central park flower valley cerise floors,1.35,11157.0,1210.0,Built Up area: 1210 (112.41 sq.m.),2,2,2,...,NaN,East,0 to 1 Year Old,"['Sector 55-56, Sector 56', 'M3m 65th Avenue M...",Ready to move in semi furnished luxury low ris...,"['3 Fan', '1 Fridge', '1 Washing Machine', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN,NaN,4.0
1108,2 BHK Flat in Sector 82 Gurgaon,flat,vatika the seven lamps,0.78,5932.0,1314.9,Super Built up area 1298(120.59 sq.m.),2,2,2,...,0.0,North-West,1 to 5 Year Old,"['SS Omnia Mall', 'Golf Course Ext Rd', 'Knowl...","Brokers excuse, 2 bhk, 1298 sq. Ft., east faci...","['1 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of...",not available,NaN
1005,2 BHK Flat in Sector 88A Gurgaon,flat,godrej oasis,0.95,7268.0,1307.1,Carpet area: 1307 (121.42 sq.m.),2,2,2,...,6.0,North-West,1 to 5 Year Old,"['Double Infinity market', 'Pataudi road', 'Dw...","Situated in sector-88a gurgaon, godrej oasis i...",[],"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4.5 out ...",not available,NaN
54,4 BHK Flat in Sector 1A IMT Manesar,flat,deepak minda,1.25,4715.0,2651.1,Carpet area: 2651 (246.29 sq.m.),4,4,3+,...,6.0,NaN,5 to 10 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...","Near by hospital,market,school highway","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Intercom Facility',...",NaN,not available,NaN

In [25]:
df.to_csv('gurgaon_properties.csv',index=False)